# test_sgs_synthetic.jl — SGS validation against a known synthetic DEM
#
# Tests the SGS solver against a programmatically generated terrain whose
# elevations, embankment heights, and notch sill levels are precisely known.
#
# Terrain (generated by generate_synthetic_dem.py):
#   - Parabolic bowl, lowest near x=0.5*Lx, slight N-S tilt.
#   - Transverse embankment at x ≈ 0.45*Lx (crest ≈ 1.5 m above datum).
#   - Notch (gap) centred at y=0.5*Ly, narrow (default 300 m), sill ≈ 0.70 m.
#   - Injection point at x=0.2*Lx, y=0.5*Ly (upstream, clear of notch).
#
# Key test assertions:
#   T0 — Mesh sanity: cells exist on both sides of the embankment.
#   T1 — SGS: No downstream flow before source WSE exceeds notch sill.
#   T2 — SGS: Downstream flow appears after notch sill exceeded.
#   T3 — SGS routes more water downstream than standard at same WSE.
#        (Standard uses max(elev_i,elev_j) sill, misses sub-cell notch.)
#   T4 — Mass balance < 0.01% for both solvers over 600 steps.
#
# Usage:
#   # Step 1 — generate the DEM (re-run if defaults changed):
#   python test/synthetic_dem/generate_synthetic_dem.py
#
#   # Step 2 — delete old meshes and regenerate (required after DEM change):
#   Remove-Item test/synthetic_dem/synthetic_mesh_sgs.parquet -ErrorAction Ignore
#   Remove-Item test/synthetic_dem/synthetic_mesh_std.parquet -ErrorAction Ignore
#
#   # Step 2 — generate meshes (once; slow, ~1-2 min each):
#   julia --threads auto FloodModel.jl \
#       --meshgen  test/synthetic_dem/synthetic_aoi.geojson \
#       --meshres  14 \
#       --dem      test/synthetic_dem/synthetic_dem.tif \
#       --meshout  test/synthetic_dem/synthetic_mesh_sgs.parquet \
#       --flow-model sgs --mesh-only
#
#   julia --threads auto FloodModel.jl \
#       --meshgen  test/synthetic_dem/synthetic_aoi.geojson \
#       --meshres  14 \
#       --dem      test/synthetic_dem/synthetic_dem.tif \
#       --meshout  test/synthetic_dem/synthetic_mesh_std.parquet \
#       --flow-model standard --mesh-only
#
#   # Step 3 — run tests:
#   julia --threads auto test/synthetic_dem/test_sgs_synthetic.jl

using Test

# ---------------------------------------------------------------------------
# Guard: only execute when run as a script
# ---------------------------------------------------------------------------
if abspath(PROGRAM_FILE) == @__FILE__

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
const TEST_DIR    = dirname(abspath(@__FILE__))
const PROJECT_DIR = dirname(dirname(TEST_DIR))

const DEM_FILE    = joinpath(TEST_DIR, "synthetic_dem.tif")
const PARAMS_FILE = joinpath(TEST_DIR, "synthetic_dem_params.json")
const AOI_FILE    = joinpath(TEST_DIR, "synthetic_aoi.geojson")
const MESH_SGS    = joinpath(TEST_DIR, "synthetic_mesh_sgs.parquet")
const MESH_STD    = joinpath(TEST_DIR, "synthetic_mesh_std.parquet")

# ---------------------------------------------------------------------------
# Prerequisites check
# ---------------------------------------------------------------------------
for f in (DEM_FILE, PARAMS_FILE, AOI_FILE)
    isfile(f) || error("""
Missing file: $f
Run first:
    python test/synthetic_dem/generate_synthetic_dem.py
""")
end

# Auto-generate meshes if absent (uses project FloodModel.jl CLI)
for (solver, out) in (("sgs", MESH_SGS), ("standard", MESH_STD))
    if !isfile(out)
        @info "Generating $solver mesh (this may take 1-2 minutes)..."
        fm = joinpath(PROJECT_DIR, "FloodModel.jl")
        run(`julia --threads auto $fm
            --meshgen $AOI_FILE --meshres 14
            --dem $DEM_FILE
            --meshout $out
            --flow-model $solver --mesh-only`)
    end
end

# ---------------------------------------------------------------------------
# Load FloodModel  (also brings JSON3, A5Grid, etc. into Main scope)
# ---------------------------------------------------------------------------
ENV["FLOODMODEL_INCLUDE_ONLY"] = "1"
include(joinpath(PROJECT_DIR, "FloodModel.jl"))
delete!(ENV, "FLOODMODEL_INCLUDE_ONLY")
_step_debug_count[] = typemax(Int)   # suppress per-step debug logging

# JSON3 is loaded by FloodModel.jl — make it available here
import JSON3

# ---------------------------------------------------------------------------
# Load known-ground-truth parameters from the DEM generator
# ---------------------------------------------------------------------------
params           = JSON3.read(read(PARAMS_FILE, String))
INJ_LON          = Float64(params["injection_lon"])
INJ_LAT          = Float64(params["injection_lat"])
INJ_Z            = Float64(params["injection_z"])           # ≈ 0.204 m
NOTCH_SILL_Z     = Float64(params["notch_sill_z"])          # ≈ 0.705 m
EMBANKMENT_Z     = Float64(params["embankment_crest_z"])    # ≈ 1.505 m
EMB_POS_FRAC     = Float64(params["embankment_pos_frac"])   # 0.45
LON0             = Float64(params["lon0"])
LON1             = Float64(params["lon1"])
HEAD_TO_NOTCH    = NOTCH_SILL_Z - INJ_Z                     # ≈ 0.50 m

@info "Synthetic DEM params loaded"
@info "  Injection z  : $(round(INJ_Z,         digits=3)) m"
@info "  Notch sill   : $(round(NOTCH_SILL_Z,  digits=3)) m  (head to notch: $(round(HEAD_TO_NOTCH,digits=3)) m)"
@info "  Emb crest    : $(round(EMBANKMENT_Z,  digits=3)) m"

println("\n", "="^62)
println("SGS synthetic DEM validation")
println("="^62)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

"""
Partition cell indices into upstream (west, injection side) and downstream
(east, beyond the embankment).

The embankment has finite width (3*sigma), so some cells straddle it.  We
classify straddling cells as downstream (conservative) by shifting the
partition boundary one full cell-width west of the embankment centreline.
This avoids falsely counting embankment cells as 'upstream' and leaking
volume into the downstream zone via centre-lon misclassification.

cell_width_deg is estimated from the domain extent and expected cell count.
"""
function partition_cells(mesh)
    emb_lon = LON0 + EMB_POS_FRAC * (LON1 - LON0)
    # Estimate one cell-width in degrees from domain extent / sqrt(n_cells)
    n = length(mesh.cells)
    domain_lon  = LON1 - LON0
    cell_width  = domain_lon / sqrt(n)   # rough; shifts partition west of emb
    split_lon   = emb_lon - cell_width   # upstream = clearly west of embankment
    up, dn = Int[], Int[]
    for (i, cell) in enumerate(mesh.cells)
        cell.center_lon < split_lon ? push!(up, i) : push!(dn, i)
    end
    return up, dn
end

"""
Advance the model `n_steps` steps of size `dt`, injecting `inj_rate_m3s`
into cell `inj_idx` before each step.  Returns (domain_vol, up_vol, dn_vol).
"""
function run_steps!(state, solver_sym, n_steps, dt, inj_idx, inj_rate_m3s,
                    up_idx, dn_idx)
    step_fn! = solver_sym == :sgs ? step_sgs! : step_standard!

    # Pre-sync water depth for standard solver (required before first step)
    if solver_sym == :standard
        for i in eachindex(state.cell_ids)
            state.cell_area[i] >= 1.0 &&
                (state.water_depth[i] = state.volume[i] / state.cell_area[i])
        end
    end

    for _ in 1:n_steps
        state.volume[inj_idx] += inj_rate_m3s * dt
        step_fn!(state, dt)
    end

    dom = sum(state.volume)
    up  = sum(state.volume[i] for i in up_idx;  init=0.0)
    dn  = sum(state.volume[i] for i in dn_idx;  init=0.0)
    return dom, up, dn
end

"""
Return the maximum water surface elevation across all upstream cells.
This reflects the water level at the embankment face — the cells immediately
west of the embankment fill first (they sit at the bowl minimum near x=Lx/2)
and their WSE is what must exceed the notch sill to drive downstream flow.
Using the injection cell WSE underestimates this because the injection cell
sits higher in the bowl (x=0.2*Lx) and fills more slowly.
"""
function max_upstream_wse(state, solver_sym, up_idx)
    best = -Inf
    for i in up_idx
        wse = if solver_sym == :sgs && !isempty(state.sgs_tables)
            tbl = state.sgs_tables[i]
            A5Grid.wse_from_volume(tbl, state.volume[i])
        else
            A = max(state.cell_area[i], 1.0)
            state.elevation[i] + state.volume[i] / A
        end
        isfinite(wse) && wse > best && (best = wse)
    end
    return best == -Inf ? 0.0 : best
end

# ---------------------------------------------------------------------------
# T0 — Mesh sanity
# ---------------------------------------------------------------------------
@testset "T0 — Mesh sanity" begin
    mesh_sgs = A5Grid.load_mesh_geoparquet(MESH_SGS)
    mesh_std = A5Grid.load_mesh_geoparquet(MESH_STD)

    @test length(mesh_sgs.cells) > 5
    @test length(mesh_std.cells) > 5

    up_sgs, dn_sgs = partition_cells(mesh_sgs)
    up_std, dn_std = partition_cells(mesh_std)

    @test length(up_sgs) >= 1
    @test length(dn_sgs) >= 1
    @test length(up_std) >= 1
    @test length(dn_std) >= 1

    @info "SGS mesh : $(length(mesh_sgs.cells)) cells  " *
          "($(length(up_sgs)) upstream, $(length(dn_sgs)) downstream)"
    @info "Std mesh : $(length(mesh_std.cells)) cells  " *
          "($(length(up_std)) upstream, $(length(dn_std)) downstream)"
    println("  T0 PASS: meshes load with cells on both sides of embankment ✓")
end

# ---------------------------------------------------------------------------
# T1 — SGS: No downstream flow before notch sill
# ---------------------------------------------------------------------------
# Inject at 50 mm/hr.  Stop once we've run 120 steps (1 hour) and verify
# that if source WSE is still below the notch sill, downstream is empty.
@testset "T1 — SGS: no downstream flow before notch sill" begin
    mesh  = A5Grid.load_mesh_geoparquet(MESH_SGS)
    state = initialise_flow_model(mesh, SGSFlow())
    up_idx, dn_idx = partition_cells(mesh)
    inj_idx, _, _  = _find_nearest_cell(mesh, INJ_LON, INJ_LAT)

    rate_m3s = (50.0 / 3_600_000.0) * state.cell_area[inj_idx]
    dt       = 30.0
    n_steps  = 60   # 30 minutes — well below notch sill at 50 mm/hr

    _, _, dn_vol = run_steps!(state, :sgs, n_steps, dt, inj_idx,
                              rate_m3s, up_idx, dn_idx)
    wse = max_upstream_wse(state, :sgs, up_idx)

    @info "T1: max upstream WSE=$(round(wse,digits=3))m  notch sill=$(round(NOTCH_SILL_Z,digits=3))m" *
          "  downstream=$(round(dn_vol,digits=2))m³"

    # The assertion is only meaningful when WSE is clearly below the sill.
    # If the 30-min run somehow already exceeded the sill, skip with @test_skip.
    if wse < NOTCH_SILL_Z
        @test dn_vol < 1.0
        println("  T1 PASS: WSE $(round(wse,digits=3))m < notch $(NOTCH_SILL_Z)m, " *
                "downstream=$(round(dn_vol,digits=3))m³ ✓")
    else
        @warn "T1: WSE already at/above notch sill after 30 min — lower injection rate"
        @test_skip dn_vol < 1.0
    end
end

# ---------------------------------------------------------------------------
# T2 — SGS: Downstream flow after notch sill exceeded
# ---------------------------------------------------------------------------
@testset "T2 — SGS: downstream flow after notch sill" begin
    mesh  = A5Grid.load_mesh_geoparquet(MESH_SGS)
    state = initialise_flow_model(mesh, SGSFlow())
    up_idx, dn_idx = partition_cells(mesh)
    inj_idx, _, _  = _find_nearest_cell(mesh, INJ_LON, INJ_LAT)

    dt  = 30.0
    tol = 1e-4

    # Phase 1: fill upstream basin to notch sill using 500 mm/hr.
    # At equilibrium WSE ≈ notch_sill; the notch then routes all excess injection.
    rate_fill = (500.0 / 3_600_000.0) * state.cell_area[inj_idx]
    wse = max_upstream_wse(state, :sgs, up_idx)
    fill_steps = 0
    while wse < NOTCH_SILL_Z - tol && fill_steps < 4800
        run_steps!(state, :sgs, 60, dt, inj_idx, rate_fill, up_idx, dn_idx)
        fill_steps += 60
        wse = max_upstream_wse(state, :sgs, up_idx)
    end

    # Phase 2: continue injecting for 3000 more steps (25 h).
    # With WSE at or above the notch sill and sustained injection, the notch
    # carries flow continuously into the downstream zone.
    run_steps!(state, :sgs, 3000, dt, inj_idx, rate_fill, up_idx, dn_idx)
    total_steps = fill_steps + 3000

    dn_vol = sum(state.volume[i] for i in dn_idx; init=0.0)
    wse    = max_upstream_wse(state, :sgs, up_idx)

    @info "T2: max upstream WSE=$(round(wse,digits=4))m after $(total_steps) steps  " *
          "downstream=$(round(dn_vol,digits=2))m³  (notch sill=$(NOTCH_SILL_Z)m)"

    # Diagnostics: show SGS z_min/z_max for upstream cells near the embankment.
    # If WSE is stalled at the notch sill, these reveal whether SGS cells have
    # z_max <= notch_sill (DEM geometry bug) rather than a physics bug.
    if wse <= NOTCH_SILL_Z + tol
        for i in up_idx
            tbl = state.sgs_tables[i]
            if tbl.z_max <= NOTCH_SILL_Z + 0.01
                @warn "T2 upstream cell $i: z_min=$(round(tbl.z_min,digits=3)) " *
                      "z_max=$(round(tbl.z_max,digits=3)) <= notch sill $(NOTCH_SILL_Z) " *
                      "— cell WSE capped at sill, cannot drive downstream flow"
            end
        end
    end

    @test wse >= NOTCH_SILL_Z - tol
    @test dn_vol > 0.0
    println("  T2 PASS: WSE=$(round(wse,digits=4))m ≈ notch sill=$(NOTCH_SILL_Z)m, " *
            "downstream=$(round(dn_vol,digits=1))m³ ✓")
end

# ---------------------------------------------------------------------------
# T3 — SGS routes more downstream water than standard at same WSE
# ---------------------------------------------------------------------------
@testset "T3 — SGS routes more water through sub-cell notch than standard" begin
    mesh_sgs = A5Grid.load_mesh_geoparquet(MESH_SGS)
    mesh_std = A5Grid.load_mesh_geoparquet(MESH_STD)
    state_sgs = initialise_flow_model(mesh_sgs, SGSFlow())
    state_std = initialise_flow_model(mesh_std, StandardFlow())

    up_sgs, dn_sgs = partition_cells(mesh_sgs)
    up_std, dn_std = partition_cells(mesh_std)
    inj_sgs, _, _  = _find_nearest_cell(mesh_sgs, INJ_LON, INJ_LAT)
    inj_std, _, _  = _find_nearest_cell(mesh_std, INJ_LON, INJ_LAT)

    rate_sgs = (500.0 / 3_600_000.0) * state_sgs.cell_area[inj_sgs]
    rate_std = (500.0 / 3_600_000.0) * state_std.cell_area[inj_std]
    dt       = 30.0
    tol      = 1e-4

    # Phase 1: fill SGS upstream basin to notch sill
    wse_sgs = max_upstream_wse(state_sgs, :sgs, up_sgs)
    steps   = 0
    while wse_sgs < NOTCH_SILL_Z - tol && steps < 4800
        run_steps!(state_sgs, :sgs, 60, dt, inj_sgs, rate_sgs, up_sgs, dn_sgs)
        steps   += 60
        wse_sgs  = max_upstream_wse(state_sgs, :sgs, up_sgs)
    end

    # Phase 2: continue 3000 more steps so notch flow accumulates
    run_steps!(state_sgs, :sgs, 3000, dt, inj_sgs, rate_sgs, up_sgs, dn_sgs)
    steps += 3000

    # Advance standard for the same total number of steps
    run_steps!(state_std, :standard, steps, dt, inj_std, rate_std, up_std, dn_std)

    dn_sgs_vol = sum(state_sgs.volume[i] for i in dn_sgs; init=0.0)
    dn_std_vol = sum(state_std.volume[i] for i in dn_std; init=0.0)
    wse_std    = max_upstream_wse(state_std, :standard, up_std)

    @info "T3 after $(steps) steps:"
    @info "  SGS: max upstream WSE=$(round(wse_sgs,digits=3))m  downstream=$(round(dn_sgs_vol,digits=1))m³"
    @info "  Std: max upstream WSE=$(round(wse_std,digits=3))m  downstream=$(round(dn_std_vol,digits=1))m³"

    @test dn_sgs_vol > dn_std_vol
    println("  T3 PASS: SGS=$(round(dn_sgs_vol,digits=1))m³ > Std=$(round(dn_std_vol,digits=1))m³ downstream ✓")
end

# ---------------------------------------------------------------------------
# T4 — Mass balance for both solvers
# ---------------------------------------------------------------------------
@testset "T4 — Mass balance: SGS and standard" begin
    for (solver_sym, mesh_file) in ((:sgs, MESH_SGS), (:standard, MESH_STD))
        mesh  = A5Grid.load_mesh_geoparquet(mesh_file)
        state = solver_sym == :sgs ?
                initialise_flow_model(mesh, SGSFlow()) :
                initialise_flow_model(mesh, StandardFlow())

        up_idx, dn_idx = partition_cells(mesh)
        inj_idx, _, _  = _find_nearest_cell(mesh, INJ_LON, INJ_LAT)
        rate_m3s = (100.0 / 3_600_000.0) * state.cell_area[inj_idx]
        dt, n_steps = 30.0, 600

        total_inj = 0.0
        step_fn!  = solver_sym == :sgs ? step_sgs! : step_standard!

        if solver_sym == :standard
            for i in eachindex(state.cell_ids)
                state.cell_area[i] >= 1.0 &&
                    (state.water_depth[i] = state.volume[i] / state.cell_area[i])
            end
        end

        for _ in 1:n_steps
            added = rate_m3s * dt
            state.volume[inj_idx] += added
            total_inj += added
            step_fn!(state, dt)
        end

        dom_vol    = sum(state.volume)
        mb_err_pct = 100.0 * abs(dom_vol - total_inj) / total_inj

        @test mb_err_pct < 0.01
        @info "T4 ($solver_sym): injected=$(round(total_inj,digits=1))m³  " *
              "domain=$(round(dom_vol,digits=3))m³  err=$(round(mb_err_pct,digits=6))%"
        println("  T4 PASS ($solver_sym): mass balance error = " *
                "$(round(mb_err_pct, sigdigits=3))% ✓")
    end
end

println("\n", "="^62)
println("All synthetic DEM SGS tests passed.")
println("="^62, "\n")

end  # if abspath(PROGRAM_FILE) == @__FILE__
